sudo: required
language: cpp

compiler: gcc
os: linux

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test

            - george-edison55-precise-backports
          packages:
            - gcc-8
            - g++-8

            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

notification:
  email: false

before_script:
  - eval "${MATRIX_EVAL}"
  - export CC=gcc-8
  - export CXX=g++-8

script:
  - mkdir ./build
  - cd ./build
  - cmake ../
  - make -j 4